server.port=8080
#????
#oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=mbc
spring.datasource.password=1234
## jpa
# ??? ?? ?? ?? ??
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
#??? sql?? ???? ????? ??
spring.jpa.properties.hibernate.format_sql=true
#???? ??? ????
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=oracle
